[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma db push --accept-data-loss --skip-generate --force-reset", "npx tsc"]

[start]
cmd = "npm start"
